apiVersion: apps/v1
kind: Deployment
metadata:
    name: gateway
    labels:
        app: gateway
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gateway
    template:
        metadata:
            labels:
                app: gateway
        spec:
            containers:
                -   name: gateway
                    image: amartellram/gateway-service:0.0.1
                    imagePullPolicy: Always
                    ports:
                    - containerPort: 8090
                    env:
                    - name: MYSQL_HOST
                      valueFrom:
                        configMapKeyRef:
                            name: mysql
                            key: database-host
                    - name: MYSQL_PORT
                      valueFrom:
                        configMapKeyRef:
                            name: mysql
                            key: database-port
                    - name: MYSQL_DATABASE
                      valueFrom:
                        configMapKeyRef:
                            name: mysql
                            key: database-name
                    - name: MYSQL_USER
                      valueFrom:
                        secretKeyRef:
                            name: mysql
                            key: database-username
                    - name: MYSQL_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: mysql
                            key: database-password
                    
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090